name: New Development Request
description: Propose a new feature or project.
title: "Feature: "
labels: ["new-request"]
body:
  - type: input
    id: requestor
    attributes:
      label: Requestor
      placeholder: e.g., Sarah
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: What problem are we solving?
    validations:
      required: true
  - type: dropdown
    id: business-value
    attributes:
      label: Business Value
      options:
        - High
        - Medium
        - Low
      default: 1
    validations:
      required: true
